name: Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4']

    steps:
    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./backend
    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: ./backend
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./backend
    - name: Generate key
      run: php artisan key:generate
      working-directory: ./backend
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./backend
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
      working-directory: ./backend
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
      working-directory: ./backend
    - name: artisan コマンドが正しく実行されるか
      run: |
        php artisan cache:clear
        php artisan config:cache
        php artisan route:clear
        php artisan view:clear
      working-directory: ./backend
  
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [laravel-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.XSERVER_SSH_KEY }}
          USER_NAME: ${{ secrets.XSERVER_USER_NAME }}
          HOST_NAME: ${{ secrets.XSERVER_HOST_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -p 10022 -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd ~/miyameshi.com/public_html/api/miya-meshi && git pull origin master && cd backend && php artisan cache:clear && php artisan config:cache && php artisan route:clear && php artisan view:clear'
